### ISSUE TITLE
[RCP Checker|HPC] Package checker not working for CosmoFlow and OpenCatalyst

### ISSUE THREAD

**Issue by koichishirahata** [mlcommons/logging#162]
@sparticlesteve @azrael417 
Package checker for CosmoFlow fails due to an error in rcp_checker.py. I found this failure can be solved by replacing `eval_accuracy` to `eval_error` in the following line. 
https://github.com/mlcommons/logging/blob/master/mlperf_logging/rcp_checker/rcp_checker.py#L62

I guess the cause of the problem is that CosmoFlow logs `eval_error` instead of `eval_accuracy`. (Therefore I guess the same failure occurs for OpenCatalyst as well.)
Could you consider updating rcp_checker.py to be compatible with CosmoFlow (and OpenCatalyst)?

**Comment by koichishirahata** [comment]
More precisely, this command fails:
`python -m mlperf_logging.package_checker FOLDER hpc 1.0.0`

**Comment by sparticlesteve** [comment]
Thanks for reporting, @koichishirahata .

Some background: in mlperf-hpc we have two benchmarks that are based on a mean-absolute-error metric instead of an "accuracy", so for cosmoflow and opencatalyst we log the metric with key `eval_error`, which apparently breaks this logic in the RCP checker.

I'm not sure what's the best way to fix it, so we'll need input from the main developers.

**Comment by shangw-nvidia** [comment]
@emizan76 Should we specify a quality metric in the RCP JSONs that include two field:
```
'quality_metric': {'name': 'eval_error', 'better_direction': 'min'}
```

This issue is similar to #79 . Essentially each benchmark needs benchmark-specific customization on metrics.

**Comment by emizan76** [comment]
Sure, that solution is good. If more HPC differences keep on creeping in like that, then we will eventually need to have two different implementations in the infra though.

**Comment by xyhuang** [comment]
Infra WG: fix after HPC submission

**Comment by sparticlesteve** [comment]
Hi all,

We will need some fix or workaround for the current submission round. I think we're happy to have something imperfect now (e.g. in a branch we can lock onto), with a properly-designed long-term solution coming after submission.

Thanks,
Steve

**Comment by shangw-nvidia** [comment]
> Hi all,
> 
> We will need some fix or workaround for the current submission round. I think we're happy to have something imperfect now (e.g. in a branch we can lock onto), with a properly-designed long-term solution coming after submission.
> 
> Thanks,
> Steve

Yes I'm working on a workaround right now (i.e., inverting the loss and use the `eval_accuracy` tag with it). The workaround would be on the benchmark itself, not on mlcommons/logging. That's why @xyhuang add that comment.

**Comment by sparticlesteve** [comment]
Ok whew, thanks for the clarification :)

**Comment by shangw-nvidia** [comment]
This issue is addressed in #166

**Comment by sparticlesteve** [comment]
Hi,

Commenting here since the PR is now merged and locked.

@shangw-nvidia I had just suggested (1-eval_error) because in practice it does tend to fall between 0 and 1, and definitely approaches 1 as does accuracy. For cosmoflow it is guaranteed because of the target value normalization. But anyway, I don't really care between (-eval_error) or (X-eval_error). I couldn't tell in the PR if the value is actually inverted, though. Are you using eval_error or -1*eval_error, or something else?

I apologize for us being such a burden. I had figured at this point that we'd have to implement a workaround ourselves but you guys have been very generous and accommodating. It is very much appreciated.

Steve

**Comment by shangw-nvidia** [comment]
> Are you using eval_error or -1*eval_error, or something else?
The compliance checker just uses `eval_error` as it is (i.e., no any transformation whatsoever). 

The RCP checker will detect if `eval_error` exists in the entire log file:
- if `eval_error` exists, use the `epoch_num` associated with `eval_error`
- if not, use the `epoch_num` associated with `eval_accuracy`

**Comment by sparticlesteve** [comment]
Ah ok, I guess I'm just not thinking straight. For the RCP checker, if it doesn't matter that eval_error is a lower-is-better metric, then your solution probably works fine for us.
