### ISSUE TITLE
Inconsistent definition of `train_samples`

### ISSUE THREAD

**Issue by hanlint** [mlcommons/logging#276]
The `train_samples` definition, as used in practice, differs depending on the benchmark. Drawing from the NVIDIA results in `v2.0` as an example:

For the Image Classification benchmark, `train_samples` is the number of samples in the ImageNet dataset, and emitted before training starts (see [file](https://github.com/mlcommons/submissions_training_2.0/blob/main/NVIDIA/results/dgxa100_ngc22.04_mxnet/resnet/result_0.txt)):
```
:::MLLOG {"namespace": "", "time_ms": 1652653456890, "event_type": "POINT_IN_TIME", "key": "train_samples", "value": 1281167, "metadata": {"file": "/workspace/image_classification/common/dali.py", "lineno": 500}}
:::MLLOG {"namespace": "", "time_ms": 1652653457111, "event_type": "POINT_IN_TIME", "key": "eval_samples", "value": 50000, "metadata": {"file": "/workspace/image_classification/common/dali.py", "lineno": 522}}
```

For the BERT benchmark, `train_samples` is the number of total samples used during training, and emitted after training is completed (see [file](https://github.com/mlcommons/submissions_training_2.0/blob/main/NVIDIA/results/2xa30_ngc22.04_pytorch/bert/result_1.txt))
```
::MLLOG {"namespace": "", "time_ms": 1652778739285, "event_type": "POINT_IN_TIME", "key": "train_samples", "value": 3172256, "metadata": {"file": "/workspace/bert/run_pretraining.py", "lineno": 1868}}
:::MLLOG {"namespace": "", "time_ms": 1652778739285, "event_type": "POINT_IN_TIME", "key": "eval_samples", "value": 10000, "metadata": {"file": "/workspace/bert/run_pretraining.py", "lineno": 1871}}
```

Since the former checks for mistakes in dataset prep, and the latter is useful in interpreting the benchmark, the suggest fix here is to split into two values:
* `dataset_train_samples`: The number of samples in the train dataset
* `total_train_samples`: Total number of samples consumed during training (e.g in the ResNet case, would be 1281167 * num_epochs)

**Comment by pgmpablo157321** [comment]
It seems this value is being checked in several places, for example:
https://github.com/mlcommons/logging/blob/d82b94d47538c6ec57ed048426fe6b515c30f96b/mlperf_logging/compliance_checker/training_2.1.0/common.yaml#L141-L144

The submission checker is not checking the exact number of total samples used during training for BERT nor for Image Classification. But it is checking for other models:
https://github.com/mlcommons/logging/blob/d82b94d47538c6ec57ed048426fe6b515c30f96b/mlperf_logging/compliance_checker/training_2.1.0/closed_unet3d.yaml#L97-L100

We could change this checks for `training_3.0.0` so that `train_samples` is replaced `dataset_train_samples` and `total_train_samples`, but the changes need to be implemented in the reference implementations.
